### ISSUE TITLE
Not Working, ballyregan.core.exceptions.NoProxiesFound: Could not find any proxies

### ISSUE THREAD

**Issue by UjjwalAggarwal-1** [idandaniel/ballyregan#2]
**Describe the bug**
I cant get any proxies, i think something is wrong

**To Reproduce**
just doing this:
fetcher = ProxyFetcher(debug=True)
proxiese = fetcher.get_one()
print(proxiese)

**Expected behavior**
get a proxy

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by idandaniel** [comment]
Hi,

NoProxiesFound exception is intentionally raised when no valid proxies could be found by the fetcher (the validator, returned empty list after validating the proxies).

I ran your code and it's working for me, so I assume the problem is with your internet connection (poor connection).

Please try again connected to another network.
If it still doesn't work, provide some more details about your infrastructure and I'll investigate it.

Hope it helped you.

**Comment by UjjwalAggarwal-1** [comment]
okay the institute's wifi was somehow preventing that, it's working using my own internet.
Thanks
