### ISSUE TITLE
Wrong detection of HTTP proxies as HTTPS proxies?

### ISSUE THREAD

**Issue by LeMoussel** [idandaniel/ballyregan#5]
**Describe the bug**
With some HTTPS proxies, got this error:
`Proxy: https://208.82.61.66:3128 is invalid. Error:HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)'))))`

It seems that there is a wrong detection of HTTP proxies as HTTPS proxies

**To Reproduce**
```python
    fetcher = ProxyFetcher(debug=False)
    proxies = fetcher.get(protocols=[Protocols.HTTPS])

    with requests.session() as reqs:
        for idx in range(len(proxies)):
            reqs.proxies.update({
                "http": str(proxies[idx]),
                "https": str(proxies[idx]),
            })
            try:
                response = reqs.get('https://api.ipify.org', timeout=15, verify=False)
                #response = reqs.get('http://httpheader.net/azenv.php', timeout=15, verify=False)
                assert response.status_code == 200
                print(f"INFO Proxy: {proxies[idx]} is valid")
            except Exception as e:
                print(f"WARNING Proxy: {proxies[idx]} is invalid. Error:{str(e)}")
```

**Expected behavior**
With this proxy  `https://168.119.175.224:3128`, changing to `http://168.119.175.224:3128`. It's OK.
Réf: [Urrlib3 - Your proxy appears to only use HTTP and not HTTPS](https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy)

**Comment by idandaniel** [comment]
Hi, thanks for opening an issue.

I tried to run your code and made some changed in it.

I discovered that when specifying in proxies both http and https, the exception is raised, but when specifying **only** the proxy protocol (https in your case) it works.
Tried it with 50 proxies, several runs.

I assume the problem is with the way you passed the proxies to the session.
here is a working code snippet:

```python
fetcher = ProxyFetcher(debug=True)
proxies = fetcher.get(
    protocols=[Protocols.HTTPS],
    limit=50
)

with requests.session() as session:
    for proxy in proxies:
        session.proxies.update({
            str(proxy.protocol): str(proxy),
        })
        try:
            response = session.get('https://api.ipify.org', timeout=15, verify=False)
            assert response.status_code == 200
            print(f"INFO Proxy: {proxy} is valid")
        except Exception as e:
            print(f"WARNING Proxy: {proxy} is invalid. Error:{str(e)}")
```

If it still doesn't work, let me know.

Hope helped you!

**Comment by idandaniel** [comment]
Hi, thank you for opening an issue.
I will investigate the problem and let you know.

**Comment by idandaniel** [comment]
After reading a bit, is saw this in urllib3 docs:
<em>
If instead you’re using urllib3 through another library like Requests there are multiple ways your proxy could be mis-configured. You need to figure out where the configuration isn’t correct and make the fix there. Some common places to look are environment variables like HTTP_PROXY, HTTPS_PROXY, and ALL_PROXY.

Ensure that the values for all of these environment variables starts with http:// and not https://
</em>

So, I modified the code like this:
```python
fetcher = ProxyFetcher(debug=False)
proxies = fetcher.get(protocols=[Protocols.HTTPS], limit=10)

with requests.session() as session:
    for proxy in proxies:
        # HERE: changing the proxy protocol to http
        proxy.protocol = Protocols.HTTP
        # But here, referring it as an https proxy
        session.proxies.update({
            'https': str(proxy),
        })
        try:
            response = session.get('https://api.ipify.org', timeout=10, verify=False)
            assert response.status_code == 200
            print(f"INFO Proxy: {proxy} is valid. Response ip: {response.text}")
        except Exception as e:
            print(f"WARNING Proxy: {proxy} is invalid.\nError:{str(e)}")
```

and it seems to work.
For my understanding, the problem is with how urllib3 treats proxies in their request.

Let me know if it helped you.
